name: Mike Vannelli
favicon: null
layout_spectrum: 0.45642
typography_spectrum: 0.15092
title: Mike Vannelli
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c6c1bc'
    - '#7f7b7a'
    - '#4e4742'
  brandStrength: 0.5
  lightness: 0.6613571904599667
  saturation: 1
  rhythmicContrast: 0.862683066399768
purpose: []
